name: desafio_bemol
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  
  get: ^4.6.5
  either_dart: ^0.1.4
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter  
  
  flutter_lints: ^2.0.0


flutter:  
  
  uses-material-design: true
  assets:
  - assets/image/



  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
